kind: pipeline
type: docker
name: default

# platform:
#   os: darwin
#   arch: arm64

steps:
- name: hello
  image: nginx
  commands:
  - echo hello world this is me binay devops guy please
 
trigger:
  branch:
    - cicd
  event:
    -  push