
# kind: pipeline
# type: docker
# name: default

# # platform:
# #   os: darwin
# #   arch: arm64

# steps:
# - name: hello
#   image: nginx
#   commands:
#   - echo hello this is it 
#   - ls 
#   - echo 
#   - echo $HOSTNAME
#   - nano a.txt
#   - apt install docker
#   - docker run -d -p 8081:80 nginx
 
# trigger:
#   branch:
#   - main



kind: pipeline
type: ssh
name: Pull image and deploy - DEV-V2

server:
  host:
    from_secret: hostname
  user:
    from_secret: host_user
  ssh_key:
    from_secret: aws-key-secret

steps:
  - name: deploy-to-remote-vm
    image: plugins/ssh
    settings:
      host: ${hostname}  # Reference the hostname from the secret
      username: ${host_user}  # Reference the username from the secret
      key:
        from_secret: aws-key-secret  # Reference the SSH key secret
      port: 2222
    commands:
        - echo $HOSTNAME
        - echo "o mere hamsafar"
        - ls
        - pwd
        - docker pull nginx
        - docker run -d -p 80:80 nginx
        

trigger:
  branch:
    - main


