
# kind: pipeline
# type: docker
# name: default

# # platform:
# #   os: darwin
# #   arch: arm64

# steps:
# - name: hello
#   image: nginx
#   commands:
#   - echo hello world this is me binay devops guy please
 
# trigger:
#   branch:
#   - main



kind: pipeline
type: docker
name: deploy-nginx

steps:
  - name: deploy-to-aws-vm
    image: plugins/ssh
    settings:
      host: 34.207.191.209
      username: ec2-user  # or any other username based on your AWS instance
      key:
        from_secret: aws-key-secret  # replace with your secret name for AWS key pair
      port: 22
      script:
        - docker pull nginx
        - docker run -d -p 80:80 nginx

trigger:
  branch:
    - main

