
kind: pipeline
type: ssh
name: Pull image and deploy - DEV-V2

server:
  host: 103.191.130.8:2222
  user:
    from_secret: host_user
  ssh_key:
    from_secret: ssh-key
  # port: 2222

steps:
  - name: deploy-to-remote-vm
    # image: plugins/ssh
    # settings:
    #   host: ${hostname}  # Reference the hostname from the secret
    #   username: ${host_user}  # Reference the username from the secret
    #   key:
    #     from_secret: ssh-key  # Reference the SSH key secret
    #   port: 2222
    commands:
        - echo $HOSTNAME
        - echo "o mere hamsafar"
        - pwd
        # - ls
        - docker pull nginx
        - docker run -d -p 80:80 nginx
        

trigger:
  branch:
    - main


